name: MCPG-Cite
main: fr.milekat.MCPG_Cite.MainCite
version: 1.0
author: MileKat
api-version: 1.16
depend: [MCPG-Core]
commands:
  shop:
    usage: "/shop help - for help"
    permission: "cite.command.shop"
    permission-message: "§cAction impossible."