name: MCPG-Cite
main: fr.milekat.MCPG_Cite.MainCite
version: 1.0
author: MileKat
api-version: 1.16
depend: [MCPG-Core, Citizens, ProtocolLib, VillagerGUIApi, WorldEdit]
commands:
  shop:
    usage: "/shop help - for help"
    permission: "modo.shop.command.shop"
    permission-message: "§cAction impossible."
  builder:
    usage: "/builder"
    permission: "modo.claim.command.buildmode"
    permission-message: "§cAction impossible."
  region:
    usage: "/region help - for help"
    permission: "modo.claim.command.region"
    permission-message: "§cAction impossible."
  mega:
    usage: "/mega <price>"
    permission: "modo.core.command.mega"
    permission-message: "§cAction impossible."
  frozen:
    usage: "/frozen help - for help"
    permission: "modo.frozen.command.frozen"
    permission-message: "§cAction impossible."